polomarte-project/config/routes.rb
PolomarteProject::Application.routes.draw do
  resources :projects
  resources :tasks
  root "projects#index"
end

polomarte-project/app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name, message: I18n.t("errors.messages.empty")

  has_many :tasks, :dependent => :destroy

  def incomplete_tasks
    tasks.where(finalized: false)
  end

  def complete_tasks
    tasks.where(finalized: true)
  end

  def finalized?
    !self.tasks.empty? && !self.tasks.any? { |task| task.finalized == false }
  end


  def status
    if finalized?
      I18n.t(:finalized, scope: [:activerecord, :attributes, :project])
    else
      I18n.t(:open, scope: [:activerecord, :attributes, :project])
    end
  end

  def percentage
    return 0 unless !complete_tasks.empty?
    complete_tasks.count.to_f / tasks.count.to_f * 100.0
  end
end

polomarte-project/app/models/task.rb
class Task < ActiveRecord::Base
  extend FriendlyId
  friendly_id :description, use: :slugged

  validates_presence_of :description, message: I18n.t("errors.messages.empty")
  validates_presence_of :project_id, message: I18n.t("errors.messages.empty")
  validates_associated :project, message: I18n.t("errors.messages.empty")

  belongs_to :project

  def status
    if finalized?
      I18n.t(:finalized, scope: [:activerecord, :attributes, :task])
    else
      I18n.t(:open, scope: [:activerecord, :attributes, :task])
    end
  end
end

polomarte-project/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: t("activerecord.attributes.project.sucess.create") }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: t("activerecord.attributes.project.sucess.update") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    Project.friendly.destroy(params[:id])
    redirect_to projects_url, notice: t("activerecord.attributes.project.sucess.destroy")
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name)
  end
end

polomarte-project/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:update, :destroy, :show, :edit]

  def create
    @task = Task.create(params[:task].permit(:description, :finalized, :project_id))
    redirect_to project_path @task.project
  end

  def update
    @task.update_attributes!(params[:task].permit(:description, :finalized, :project_id))
    respond_to do |format|
      format.html { redirect_to project_path @task.project }
      format.js
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path @task.project }
      format.js
    end
  end

  def show
  end

  def edit
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:description, :finalized, :project_id)
  end
end

polomarte-project/app/helpers/application_helper.rb
module ApplicationHelper

  def errors(model)
    render partial: "layouts/errors",
           locals: {model: model}
  end

  def notices
    render partial: "layouts/notice"
  end

  def tasks_modal(projects)
    render partial: "projects/task_modal",
           locals: {projects: projects}
  end
end

polomarte-project/app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
    <% model.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
    <% end %>
<% end %>

polomarte-project/app/views/layouts/_notice.html.erb
<% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
<% end %>

polomarte-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(:project, scope: [:activerecord, :models]).pluralize.capitalize %></title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

polomarte-project/app/views/projects/_errors.html.erb
<% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
    <% end %>
<% end %>

polomarte-project/app/views/projects/_form.html.erb
<%= errors @project %>

<%= form_for(@project, :class => 'form') do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name, :class => 'form-control', :autofocus => true %>

    </div>

    <%= f.submit :class => 'btn btn-primary', :value => t("helpers.submit.submit", model: t("activerecord.models.project")) %>
    <%= link_to t("helpers.cancel.back"), projects_path, :class => "btn btn-default" %>

<% end %>

polomarte-project/app/views/projects/_task_modal.html.erb
<% projects.each do |project| %>
    <div class="modal fade" id='task-modal-<%= project.id %>'>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><%= link_to project.name, project %></h4>
          </div>
          <div class="modal-body">
            <% project.tasks.each do |task| %>
                <ul>
                  <li><p><%= link_to task.description, edit_task_path(task) %> (<%= task.status.capitalize %>)</p></li>
                </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

polomarte-project/app/views/projects/edit.html.erb
<h1><%= t("helpers.submit.update", model: t("activerecord.models.project")) %></h1>

<%= render 'form' %>

polomarte-project/app/views/projects/index.html.erb
<%= link_to t("helpers.submit.create", model: t("activerecord.models.project")), new_project_path, :class => 'btn btn-primary btn-lg' %>
<h1><%= t(:project, scope: [:activerecord, :models]).pluralize.capitalize %></h1>

<table class="table">

  <thead>
  <tr>
    <th><%= t("activerecord.attributes.project.name") %></th>
    <th></th>
    <th></th>
    <th class="centered"><%= t("activerecord.attributes.project.status") %></th>
    <th class="centered"><%= t("activerecord.attributes.project.conclusion") %></th>
    <th class="centered"><%= t("activerecord.models.task").capitalize.pluralize %></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td class="centered"><%= link_to image_tag("edit.png"), edit_project_path(project) %></td>
        <td class="centered"><%= link_to image_tag("trash.png"), project, method: :delete, data: {confirm: t("general.messages.confirmation")} %></td>
        <td class="centered"><%= project.status %></td>
        <td class="centered"><%= number_to_percentage(project.percentage, delimiter: '.', separator: ',', precision: 2) %></td>
        <td class="centered">
          <a data-toggle="modal" href='#task-modal-<%= project.id %>'> <%= pluralize project.tasks.size, t("activerecord.models.task") %> </a>
        </td>
      </tr>
  <% end %>
  </tbody>

</table>

<%= tasks_modal @projects %>

polomarte-project/app/views/projects/new.html.erb
<h1><%= t(:create, scope: [:helpers, :submit], model: t(:project, scope: [:activerecord, :models])) %></h1>

<%= render 'form' %>

polomarte-project/app/views/projects/show.html.erb
<%= notices %>
<%= errors @project %>

<spam class="project-title"><%= @project.name %> (<%= @project.status %>)</spam>
<%= link_to t("helpers.submit.rename"), edit_project_path(@project), :class => "btn btn-default" %>

<br/><br/>

<div id="project" class="form-group">

  <div id="task-form" class="task-form">
    <%= form_for(@project.tasks.build, :class => 'form') do |f| %>
        <%= f.hidden_field :project_id %>
        <%= f.text_field :description, class: "form-control", :autofocus => true %>
        <br>
        <%= f.submit :class => 'btn btn-primary', :value => t("helpers.submit.submit", model: t("activerecord.models.task")) %>
    <% end %>
  </div>


  <%# link_to_function is deprecated %>
  <% #http://guides.rubyonrails.org/working_with_javascript_in_rails.html#unobtrusive-javascript      %>
  <a href="#" onclick='enableTaskForm()' class="btn btn-primary" id="task-add"> <%= t("helpers.submit.create", model: t("activerecord.models.task")) %> </a>


  <hr>

  <h2><%= t("activerecord.models.task").pluralize.capitalize %> <%= t("activerecord.attributes.task.incomplete").pluralize %></h2>

  <div class="tasks" id="incomplete_tasks">
    <%= render @project.incomplete_tasks %>
  </div>
  <hr>

  <h3><%= t("activerecord.models.task").pluralize.capitalize %> <%= t("activerecord.attributes.task.complete").pluralize %></h3>

  <div class="tasks" id="complete_tasks">
    <%= render @project.complete_tasks %>
  </div>

  <br>

<%= link_to t("helpers.cancel.back"), root_path, class: "btn btn-default" %>

polomarte-project/app/views/tasks/_form.html.erb
<%= errors @task %>

<%= form_for(@task, :class => 'form') do |f| %>

    <div class="form-group">
      <%= f.label :description %>
      <br>
      <%= f.text_field :description, :class => 'form-control', :autofocus => true %>
      <br>
      <%= f.check_box :finalized %>
      <%= f.label t("activerecord.attributes.task.finalized") %>

    </div>

    <%= f.submit :class => 'btn btn-primary', :value => t("helpers.submit.submit", model: t("activerecord.models.task")) %>
    <%= link_to t("helpers.cancel.back"), project_path(@task.project), :class => "btn btn-default" %>

<% end %>

polomarte-project/app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>

    <%= f.check_box :finalized, class: "edit_task", id: "task-finalized-#{task.id}" %>
    <%= f.label :finalized, task.description, class: ("finalized-task" if task.finalized) %>

    <%= link_to t("helpers.submit.edit"), edit_task_path(task) %> | <%= link_to t("helpers.submit.remove"), task, method: :delete, data: {confirm: t("general.messages.confirmation")}, remote: true %>
<% end %>

polomarte-project/app/views/tasks/create.js.erb
$('#new_task')[0].reset();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

polomarte-project/app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

polomarte-project/app/views/tasks/edit.html.erb
<h1><%= t("helpers.submit.update", model: t("activerecord.models.task")) %></h1>

<%= render 'form' %>

polomarte-project/app/views/tasks/show.html.erb
<%= notices %>
<%= errors @task %>


<h1><%= @task.description %> (<%= @task.finalized %>) </h1><%= link_to 'Edit', edit_task_path(@task) %>

<%= link_to t("helpers.cancel.back"), root_path, class: "btn btn-default" %>

polomarte-project/app/views/tasks/update.js.erb
<% if @task.finalized? %>
$('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
$('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>