config/routes.rb
Polomarte::Application.routes.draw do
  resources :projects do
    member do
      get 'new_task'
    end
  end

  resources :tasks do
    member do
      post 'check'
    end
  end

  resources :tasks do
    member do
      post 'uncheck'
    end
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, :inverse_of => :project, :dependent => :delete_all

	validates :name, presence: true
	validates :name, length: { maximum: 255 }

	accepts_nested_attributes_for :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :new_task]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # Cria Nova Tarefa
  def new_task
    @task = Task.new(project_id: @project.id)  
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, tasks_attibutes: [:name, :description, :completed, :project_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/addtask.html.erb
<h1>Adicionar Tarefa ao Projeto: <%= @project.name %> </h1>

<%= render 'tasks/form', readonly: true, :cancel_path => project_path(@project) %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<% if @projects.empty? %>
  <p>No projects found</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td class = "finished">
            <%= project.tasks.all? { |task| task.completed == true } && project.tasks.any? ? "(finalizado)" : "" %>
          </td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_project_path(project), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        project_path(project),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

  <%= link_to t('.new', :default => t("Novo Projeto")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/new_task.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => @project.name, :model => model_class.model_name.human.titleize %></h1>
</div>
<h1>New Task</h1>

<%= render 'tasks/form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default =>@project.name.titleize %></h1>
</div>

<% if @project.tasks.empty? %>
  <p>No tasks found</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= "Tasks" %></th>
        <th></th>
        <th></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @project.tasks.each do |task| %>
        <tr>
          <td>
            <% if task.completed %>
              <%= form_tag(uncheck_task_url(task), method: "post", :class => "icon-img") do %>
                <%= image_submit_tag("checkbox_checked.png", :class => "icon-img") %>
              <% end %>
            <% else %>
              <%= form_tag(check_task_url(task), method: "post", :class => "icon-img") do %>
                <%= image_submit_tag("checkbox_unchecked.png", :class => "icon-img") %>
              <% end %>
            <% end %>
          </td>
          
          <td><%= link_to task.name, task %></td>
          <td class="finished"><%= task.completed ? "(finalizada)" : "" %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_task_path(task), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        task,
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="form-actions">
  <%= link_to 'Nova Tarefa', new_task_project_path(@project), :class => 'btn btn-primary' %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
</div>